### ISSUE TITLE
Model and Inference code for DFFD dataset

### ISSUE THREAD

**Issue by SifatMd** [crywang/RFM#14]
Hi! Can you please give me the code and model for the DFFD dataset? Do you have a model trained separately on Group B dataset? Or are they combined? If you have one trained only on Group B, that would be more helpful, but if you have trained on the whole DFFD dataset, that would work too. My email: sifat@vt.edu 

Thank you.

**Comment by crywang** [comment]
The pre-trained model on the whole DFFD dataset has been send to you.
