### ISSUE TITLE
Datasets youtube, celeba_2w, and "-Img"

### ISSUE THREAD

**Issue by yuntianlong2002** [crywang/RFM#19]
Hi! 

I don't see youtube and celeba_2w in the DFFD in the datasets, is there an updated names for them?
Also I am wondering why do we have add "-Img" to the CelebDF dataset, is there a dataset preprocessing script to generate them?

**Comment by rensheng2022** [comment]
youtube应该是FF++里的吧，我也有此疑问

**Comment by crywang** [comment]
The 'celeba_2w' represents CelebA used in DFFD. And you can find "We further utilize the source frames from FaceForensics++ [42] as additional real faces." in the DFFD paper.

**Comment by crywang** [comment]
Of crouse, a dataset preprocessing script was used to generate the dataset.

**Comment by chenyize111** [comment]
can you post the script to generate the dataset
