### ISSUE TITLE
weights file

### ISSUE THREAD

**Issue by wuqile123456** [crywang/RFM#20]
Hi, can you provide me with the weights file that you have trained?

**Comment by crywang** [comment]
could you give me an email address?

**Comment by wuqile123456** [comment]
> 

OK, this is my address:972269148@qq.com

**Comment by bunnuzhou** [comment]
> could you give me an email address?

Sorry for bothering you again, I'm desperating to get a quick start of your work nowadays. Would you mind provide your trained weights again? My email is 1018553676@qq.com.
