### ISSUE TITLE
About Black Box Experiment

### ISSUE THREAD

**Issue by MetroTY** [crywang/RFM#24]
![image](https://github.com/crywang/RFM/assets/106897090/0a9ab04b-3e89-4932-a308-6710628d1089)
Hi author, I'm a little confused about this graph in the paper, you said "From the matrix, FaceAPP belongs to the one-stage manipulation technique", here when RFM is not used, FaceAPP with one-stage forgery methods (face2face, faceapp) (b) is obviously better than the effect of using RFM(a).Because the disparity in their resemblance is much more pronounced？

**Comment by crywang** [comment]
Yes, you're right. This is a typo
